# include: package:pedantic/analysis_options.yaml
# include: package:lint/analysis_options.yaml
include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude: [build/**]

linter:
  rules:
    omit_local_variable_types: false
    lines_longer_than_80_chars: false
    public_member_api_docs: false
