name: todos
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.5
  flutter_redux: ^0.7.0
  flutter_svg: 0.19.1
  google_fonts: ^1.1.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  mockito: ^4.1.3
  modal_bottom_sheet: ^1.0.0+1
  oktoast: ^2.3.2
  path_provider: ^1.6.27
  redux_epics: ^0.14.0
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.10.3
  hive_generator: 0.8.1
  very_good_analysis: ^1.0.4

# Hive_Generator Error https://github.com/hivedb/hive/issues/390#issuecomment-756821430
dependency_overrides:
  analyzer: 0.40.4

flutter:
  uses-material-design: true

  assets:
    - assets/
